name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      HF: ${{ secrets.HF }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Add remote
        run: git remote add space https://mshoush:$HF@huggingface.co/spaces/MShoush/mlops-demo2

      - name: Push to hub
        run: git push --force space main
