name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
          # https://huggingface.co/spaces/MShoush/mlops-demo2
        run: git remote add space https://MShoush:$HF@huggingface.co/spaces/MShoush/mlops-demo2
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://MShoush:$HF@huggingface.co/spaces/MShoush/mlops-demo2 main
